### ISSUE TITLE
missing '/' in name/location of <diagnosticFile> for some of the RetrieveXXX.xml config files

### ISSUE THREAD

**Issue by andrewcoc** [Deltares/CanOpenFEWS#1]
It appears a few of the RetrieveXXXX (ex. RetrieveRDPS.xml) files in the moduleconfigfiles/import/ecccgrids directory is missing a forward slash in the definition of the <diagnosticFile> name/location. See below, where it should have a forward slash after the word “work”.
 
 
                <general>
                                <piVersion>1.8</piVersion>
                                <rootDir>%REGION_HOME%/modules/pyscripts</rootDir>
                                <workDir>%ROOT_DIR%/work</workDir>
                                <exportDir>$IMPORT_FOLDER$/RDPS</exportDir>
                                <importDir>$IMPORT_FOLDER$/RDPS</importDir>
                                <dumpFileDir>$GA_DUMPFILEDIR$</dumpFileDir>
                                <dumpDir>%ROOT_DIR%/work</dumpDir>
                                <diagnosticFile>%ROOT_DIR%/workfews_data_download_log.xml</diagnosticFile>
                                <convertDatum>false</convertDatum>
                </general>
                <activities>
                                <startUpActivities>

**Comment by DaveCasson** [comment]
Thanks Andrew, this is closed with commit: https://github.com/Deltares/CanOpenFEWS/commit/ad317640ad056e13eb4399c0966ae442a41b7c94
