### ISSUE TITLE
inconsistent snowdata import

### ISSUE THREAD

**Issue by andrewcoc** [Deltares/CanOpenFEWS#2]
I noticed that there are 4 PreprocessXXXXX.xml files in the moduleconfigfiles/preprocess/SnowData directory.

The PreprocessSNODAS.xml and PreprocessSnowcast.xml are not used, as the example configuration for retrieve/import/preprocess of SNODAS and Snowcast data uses the PreprocessSnowTemplate.xml.

It seems like the GlobSnow config should also use the PreprocessSnowTemplate.xml to be consistent, and the other preprocessXXXXX.xml files should be deleted to reduce confusion.

Thanks,
Andrew

**Comment by andrewcoc** [comment]
Referring to my comment above, it isn't completely correct. I just realized that Snowcast also uses its own PreprocessSnowcast.xml, so only SNODAS is using the PreprocessSnowTemplate.xml

**Comment by DaveCasson** [comment]
Thanks Andrew. This is updated with Commit: https://github.com/Deltares/CanOpenFEWS/commit/7e9b9382be4bb337c069e461ceb44f3ee31e1b00
